[package]
name = "cars"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
color-eyre = "0.6.3"
ctrlc = "3.4.6"
ratatui = "0.29.0"
crossterm = "0.28.1"

